### ISSUE TITLE
…/kak/autoload/: No such file or directory

### ISSUE THREAD

**Issue by basbebe** [jbomanson/search-doc.kak#2]
Hi!

I don't get any autocompletions / suggestions and an error `No such doc file:`

I'm getting this in my debug buffer:

```console
shell stderr: <<<
find: /Users/XZY/.config/kak/autoload/: No such file or directory
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]
>>>
shell stderr: <<<
find: /Users/XZY/.config/kak/autoload/: No such file or directory
>>>
Error: No such doc file:
```

I'm on macOS (which is why there is nothing in `~/.config/.kak/autoload` but in `/usr/local/share/kak/autoload` which is symlinked to `/usr/local/Cellar/kakoune/HEAD-26cf5cd/share/kak/rc`)

**Comment by jbomanson** [comment]
Hello,

Thanks for the bug report and the details!

The way in which search-doc looks for documentation files is identical to the `doc` command that comes with kakoune. Namely, both commands look for an autoload directory under %val(config) and then doc and rc directories under %val(runtime). Hence, the cause of your problem _might_ lie in kakoune or your installation.

Given the errors in your debug buffer, it seems that the kakoune value %val(config) points to ~/.config/.kak on your end, which is a problem. This problem is tricky because %val(config) is a value that you can not change unlike options of the form %opt(...). Moreover, the fact that also `doc` depends on it suggests that indeed the problem might be not specific to search-doc.

In order to check this reasoning, could you determine:

1. What does the following print for you?
```
echo -debug %val(config)
echo -debug %val(runtime)
```

2. Does `:doc` work for you? For reference, when you are typing an argument for it, it should give you the following kinds of suggestions: buffers, changelog, command-parsing, commands, ....

In any case, I could update search-doc so that you can configure the search path for documentation. However, that would basically be a workaround and not fix for the root cause in this case, if the above reasoning holds. Furthermore, I would prefer to keep the search for documentation aligned with `doc` as much as possible.

**Comment by basbebe** [comment]
Hi!

From what I understand this is because of the way macOS installation of kakoune and autoload is handled:

https://github.com/mawww/kakoune/issues/1063

https://github.com/mawww/kakoune/wiki/Running-commands-at-startup


this is what `echo -debug %val(config)` and `echo -debug %val(runtime)` give me (which should be typical for any mac installation):

```console
/Users/XYZ/.config/kak
/usr/local/Cellar/kakoune/HEAD-26cf5cd/share/kak
```

`:doc` works fine for me.

**Comment by jbomanson** [comment]
Thanks for the extra information!

I realized there are two orthogonal problems here:
- the lookup of some paths that do not exist
- the use of grep with the -P argument on macOS 

I just updated the master branch with a new version that _hopefully_ fixes these problems. Please let me know if it works for you.

Cheers!

**Comment by basbebe** [comment]
works now, thanks!!
